/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll;

import static Payroll.Login.user;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Ruth
 */
public class Employee extends javax.swing.JFrame {
    Menu m = new Menu(user);

    /**
     * Creates new form Employees
     */
    public Employee() {
        initComponents();
        //init departments
        fillDepartment();
        fillDesignation();
    }
      public final void fillDepartment(){
        
        try {
           Connection con = DBConnect.connect();
            String sql = "select * FROM departments";
            DBConnect.ps = con.prepareStatement(sql);
            DBConnect.rs = DBConnect.ps.executeQuery();
            cboDep.removeAllItems();
            // depIDlist.removeAll(depIDlist);
            while(DBConnect.rs.next()) {
                cboDep.addItem(DBConnect.rs.getString(2));
               // depIDlist.add(Integer.toString(DBConnect.rs.getInt(1)));
            }
            con.close();
        } catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null, ex);

        }
}
            public final void fillDesignation(){
         if(cboDep.getItemCount() > 1){
        try {
           Connection con = DBConnect.connect();
            String sql = "select * FROM sub_departments where department = '"+cboDep.getSelectedItem().toString()+"'";
            DBConnect.ps = con.prepareStatement(sql);
            DBConnect.rs = DBConnect.ps.executeQuery();
            cboDes.removeAllItems();
            // depIDlist.removeAll(depIDlist);
            if(DBConnect.rs.next())
            {
                 cboDes.addItem(DBConnect.rs.getString(3));
            while(DBConnect.rs.next()) {
                cboDes.addItem(DBConnect.rs.getString(3));
               // depIDlist.add(Integer.toString(DBConnect.rs.getInt(1)));
            }
            }
            else
            {
                 cboDes.removeAllItems();
             cboDes.addItem("No designations");
            }
            con.close();
        } catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null, ex);

        }
         }
         else
         {
             cboDes.removeAllItems();
             cboDes.addItem("No designations");
         }
}
    // Displaying the image in a label
   public ImageIcon ResizeImage (String imagePath, byte[] pic) {
    ImageIcon myImage;
    if (imagePath != null) {
    myImage = new ImageIcon (imagePath);
    } else if ( pic != null)
    {
    myImage = new ImageIcon (pic);
    }
    else
    {
        return null;
    }
    Image img = myImage.getImage();
    Image img2 = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon Image = new ImageIcon (img2);
    return Image;
    }
   
   // Clear textfields and textareas
    public void clrField (JPanel p) {
for (Component C : p.getComponents())
{    
    if (C instanceof JTextField){

        ((JTextComponent) C).setText("");
    }
    if (C instanceof JTextArea){

        ((JTextComponent) C).setText("");
    }
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowEmployees = new javax.swing.JDialog();
        Header1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblshowemployees = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        searchemployee = new javax.swing.JTextField();
        selecttbl = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        personalInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        cboGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        workInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        cboDep = new javax.swing.JComboBox<>();
        joindate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        cboPay = new javax.swing.JComboBox<>();
        cboDes = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCIr = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnBack = new javax.swing.JLabel();

        ShowEmployees.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ShowEmployees.setAlwaysOnTop(true);
        ShowEmployees.setBackground(new java.awt.Color(255, 255, 255));
        ShowEmployees.setMinimumSize(new java.awt.Dimension(845, 523));

        Header1.setBackground(new java.awt.Color(18, 19, 34));
        Header1.setMinimumSize(new java.awt.Dimension(776, 72));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Payroll System");
        jLabel15.setIconTextGap(5);

        jLabel16.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Employees");

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Header1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ShowEmployees.getContentPane().add(Header1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblshowemployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Surname", "Other names", "Department", "Designation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblshowemployees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblshowemployees);
        if (tblshowemployees.getColumnModel().getColumnCount() > 0) {
            tblshowemployees.getColumnModel().getColumn(0).setResizable(false);
            tblshowemployees.getColumnModel().getColumn(1).setResizable(false);
            tblshowemployees.getColumnModel().getColumn(2).setResizable(false);
            tblshowemployees.getColumnModel().getColumn(3).setResizable(false);
            tblshowemployees.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("search names or departments or designations");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_20px.png"))); // NOI18N

        searchemployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchemployee.setToolTipText("Search by employee name");
        searchemployee.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchemployeeCaretUpdate(evt);
            }
        });

        selecttbl.setBackground(new java.awt.Color(45, 43, 63));
        selecttbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecttbl.setForeground(new java.awt.Color(255, 255, 255));
        selecttbl.setText("Select employee");
        selecttbl.setBorderPainted(false);
        selecttbl.setContentAreaFilled(false);
        selecttbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selecttbl.setOpaque(true);
        selecttbl.setPreferredSize(new java.awt.Dimension(74, 22));
        selecttbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecttblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(selecttbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecttbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        ShowEmployees.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(845, 523));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        Header.setBackground(new java.awt.Color(18, 19, 34));
        Header.setMinimumSize(new java.awt.Dimension(776, 72));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payroll System");
        jLabel7.setIconTextGap(5);

        jLabel8.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EMPLOYEES");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Body.setBackground(new java.awt.Color(255, 255, 255));

        personalInfo.setBackground(new java.awt.Color(255, 255, 255));
        personalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date of Birth");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Phone number");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Image");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Surname");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Other Names");

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBrowse.setBackground(new java.awt.Color(45, 43, 63));
        btnBrowse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBrowse.setText("Browse image");
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowse.setOpaque(true);
        btnBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseMouseClicked(evt);
            }
        });

        dob.setDateFormatString("yyyy-MM-dd");
        dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Address");

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout personalInfoLayout = new javax.swing.GroupLayout(personalInfo);
        personalInfo.setLayout(personalInfoLayout);
        personalInfoLayout.setHorizontalGroup(
            personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoLayout.createSequentialGroup()
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(56, 56, 56)
                        .addComponent(txtAddress))
                    .addGroup(personalInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(45, 45, 45)
                                .addComponent(txtFname))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(20, 20, 20)
                                .addComponent(txtLname))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(69, 69, 69)
                                .addComponent(txtmail))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(cboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(9, 9, 9)
                                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhone)
                                    .addGroup(personalInfoLayout.createSequentialGroup()
                                        .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))))))
                .addGap(15, 15, 15))
        );
        personalInfoLayout.setVerticalGroup(
            personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInfoLayout.createSequentialGroup()
                        .addGroup(personalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(personalInfoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        workInfo.setBackground(new java.awt.Color(255, 255, 255));
        workInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        workInfo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Joining Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Department");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Designation");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("<html>Other<br>information</html>");

        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfo.setRows(5);
        txtInfo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInfo);

        cboDep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepActionPerformed(evt);
            }
        });

        joindate.setDateFormatString("yyyy-MM-dd");
        joindate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Payment mode");

        cboPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cheque", "Cash", "Bank" }));

        cboDes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboDes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please choose department" }));

        javax.swing.GroupLayout workInfoLayout = new javax.swing.GroupLayout(workInfo);
        workInfo.setLayout(workInfoLayout);
        workInfoLayout.setHorizontalGroup(
            workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workInfoLayout.createSequentialGroup()
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workInfoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                            .addGroup(workInfoLayout.createSequentialGroup()
                                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(workInfoLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(joindate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(workInfoLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(cboDes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(workInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addGap(10, 10, 10)
                        .addComponent(cboPay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        workInfoLayout.setVerticalGroup(
            workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workInfoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(joindate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboDep, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDes))
                .addGap(10, 10, 10)
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboPay)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 10, 5));

        btnCIr.setBackground(new java.awt.Color(45, 43, 63));
        btnCIr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCIr.setForeground(new java.awt.Color(255, 255, 255));
        btnCIr.setText("Clear Fields");
        btnCIr.setBorderPainted(false);
        btnCIr.setContentAreaFilled(false);
        btnCIr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCIr.setOpaque(true);
        btnCIr.setPreferredSize(new java.awt.Dimension(74, 22));
        btnCIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCIrActionPerformed(evt);
            }
        });
        jPanel1.add(btnCIr);

        btnSave.setBackground(new java.awt.Color(45, 43, 63));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save new");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.setPreferredSize(new java.awt.Dimension(74, 22));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);

        btnUpdate.setBackground(new java.awt.Color(45, 43, 63));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setEnabled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.setPreferredSize(new java.awt.Dimension(74, 22));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setBackground(new java.awt.Color(45, 43, 63));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.setOpaque(true);
        btnDelete.setPreferredSize(new java.awt.Dimension(74, 22));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnSelect.setBackground(new java.awt.Color(45, 43, 63));
        btnSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setText("Select employee");
        btnSelect.setBorderPainted(false);
        btnSelect.setContentAreaFilled(false);
        btnSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelect.setOpaque(true);
        btnSelect.setPreferredSize(new java.awt.Dimension(74, 22));
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect);

        btnBack.setBackground(new java.awt.Color(18, 19, 34));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setOpaque(true);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(workInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(personalInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Body, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked
static File img = null;
static FileInputStream fis = null;
    private void btnBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseMouseClicked
        // TODO add your handling code here:
        String imgPath = null;
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "png", "jpg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                lblImage.setIcon(ResizeImage(path, null));
                img = selectedFile;
                fis =  new FileInputStream(selectedFile);
                imgPath = path;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No File Selected");
        }
    }//GEN-LAST:event_btnBrowseMouseClicked

    private void btnCIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCIrActionPerformed
        // TODO add your handling code here:

           txtFname.setText("");
                   txtLname.setText("");
              txtAddress.setText("");
               txtmail.setText("");
                 txtPhone.setText("");
  txtInfo.setText("");
  employeenum = "";
  btnSave.setEnabled(true);
 btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            
             img = null;
 fis = null;
 lblImage.setIcon(ResizeImage(null, null));
    }//GEN-LAST:event_btnCIrActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            if(!txtFname.getText().equals(""))
        {
         try {
          Connection con = DBConnect.connect();
        
            String sql = "INSERT INTO `employees`(`surname`, `other_names`, `gender`, `dob`, `address`, `email`, `phone`,"
                    + " `img`, `joindate`, `department`, `designation`, `payment`, `other`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            // java.sql.Date date1 = new java.sql.Date(FromEv.getDate().getTime());
            //java.sql.Date date2 = new java.sql.Date(ToEv.getDate().getTime());
            DBConnect.ps = con.prepareStatement(sql);
            DBConnect.ps.setString(1, txtFname.getText());
             DBConnect.ps.setString(2, txtLname.getText());
              DBConnect.ps.setString(3, cboGender.getSelectedItem().toString());
               java.sql.Date date1 = new java.sql.Date(dob.getDate().getTime());
               DBConnect.ps.setDate(4, date1);
               DBConnect.ps.setString(5, txtAddress.getText());
               DBConnect.ps.setString(6, txtmail.getText());
               DBConnect.ps.setString(7, txtPhone.getText());
               DBConnect.ps.setBinaryStream(8, (InputStream)fis, (int)(img.length()));
            java.sql.Date date2 = new java.sql.Date(joindate.getDate().getTime());
               DBConnect.ps.setDate(9, date2);
                  DBConnect.ps.setString(10, cboDep.getSelectedItem().toString());
   DBConnect.ps.setString(11, cboDes.getSelectedItem().toString());
 DBConnect.ps.setString(12, cboPay.getSelectedItem().toString());
  DBConnect.ps.setString(13, txtInfo.getText());
            DBConnect.ps.execute();
            JOptionPane.showMessageDialog(null, "NEW RECORD SAVED");
             con.close();
                    img = null;
 fis = null;
        } catch (SQLException e ) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else
            JOptionPane.showMessageDialog(null, "Name is empty!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
              if("".equals(employeenum))
        {
            JOptionPane.showMessageDialog(null, "ID NEEDED. CLICK RECORD FROM TABLE");
        }
        else
        {

            try {
                 Connection con = DBConnect.connect();
                String query = "UPDATE `employees` SET `surname`=?,`other_names`=?,"
                        + "`gender`=?,`dob`=?,`address`=?,`email`=?,`phone`=?,"
                        + "`img`=?,`joindate`=?,`department`=?,`designation`=?,`payment`"
                        + "=?,`other`=? where id = ?";
               DBConnect.ps = con.prepareStatement(query);
            DBConnect.ps.setString(1, txtFname.getText());
             DBConnect.ps.setString(2, txtLname.getText());
              DBConnect.ps.setString(3, cboGender.getSelectedItem().toString());
               java.sql.Date date1 = new java.sql.Date(dob.getDate().getTime());
               DBConnect.ps.setDate(4, date1);
               DBConnect.ps.setString(5, txtAddress.getText());
               DBConnect.ps.setString(6, txtmail.getText());
               DBConnect.ps.setString(7, txtPhone.getText());
               if (lblImage.getIcon() == null || fis == null || img == null) {
  // this means there is no icon
   DBConnect.ps.setBinaryStream(8, null);
}
               else
               {
              DBConnect.ps.setBinaryStream(8, (InputStream)fis, (int)(img.length()));
               }
            java.sql.Date date2 = new java.sql.Date(joindate.getDate().getTime());
               DBConnect.ps.setDate(9, date2);
                  DBConnect.ps.setString(10, cboDep.getSelectedItem().toString());
   DBConnect.ps.setString(11, cboDes.getSelectedItem().toString());
 DBConnect.ps.setString(12, cboPay.getSelectedItem().toString());
  DBConnect.ps.setString(13, txtInfo.getText());
  DBConnect.ps.setString(14, employeenum);
                DBConnect.ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"RECORD UPDATED SUCCESSFULLY");
                con.close();
                      img = null;
 fis = null;
            }
            catch (SQLException ex ) {
                JOptionPane.showMessageDialog(null, ex);

            }}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         if(!"".equals(employeenum)){
           try {
              
            Connection con = DBConnect.connect();
            String query = "DELETE FROM employees WHERE id = ?";
            DBConnect.ps = con.prepareStatement(query);
            DBConnect.ps.setInt  (1, Integer.parseInt(employeenum));
            DBConnect.ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "Record Deleted");
                   img = null;
 fis = null;
        } catch (SQLException e ) {
            JOptionPane.showMessageDialog(null, e);
        }
       txtFname.setText("");
                   txtLname.setText("");
              txtAddress.setText("");
               txtmail.setText("");
                 txtPhone.setText("");
                 
  txtInfo.setText("");
          btnSave.setEnabled(true);
             btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        employeenum = "";
        lblImage.setIcon(ResizeImage(null, null));
         }
         else
             JOptionPane.showMessageDialog(null, "ID NEEDED. CLICK RECORD FROM TABLE");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
         ShowEmployees.setVisible(true);
        FillTable(tblshowemployees,"SELECT `id`, `surname` , other_names, department, designation from employees");
        ShowEmployees.pack();
        CenteredDialog(ShowEmployees);
    }//GEN-LAST:event_btnSelectActionPerformed

    private void searchemployeeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchemployeeCaretUpdate
        // TODO add your handling code here:
        FillTable(tblshowemployees,"SELECT `id`, `surname` , other_names, department, designation from employees where "
            + "surname LIKE '%" + searchemployee.getText() + "%' "
            + " OR other_names LIKE  '%" + searchemployee.getText() + "%' "
            + "OR department LIKE '%" + searchemployee.getText() + "%' "
            + "OR designation LIKE '%" + searchemployee.getText() + "%' ");
    }//GEN-LAST:event_searchemployeeCaretUpdate
    static String employeenum = "";
    private void selecttblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecttblActionPerformed
        // TODO add your handling code here:
             int selectedRow = tblshowemployees.getSelectedRow();
        String hid = tblshowemployees.getValueAt(selectedRow, 0).toString();
        try {
           Connection con = DBConnect.connect();
            String sql = "select * FROM employees WHERE id = ?";
            DBConnect.ps = con.prepareStatement(sql);
            DBConnect.ps.setString(1,hid);
            DBConnect.rs = DBConnect.ps.executeQuery();
            if(DBConnect.rs.next()) {
                       img = null;
 fis = null;
                 txtFname.setText(DBConnect.rs.getString(2));
                   txtLname.setText(DBConnect.rs.getString(3));
            cboGender.setSelectedItem(DBConnect.rs.getString(4));
            dob.setDate(DBConnect.rs.getDate(5));
              txtAddress.setText(DBConnect.rs.getString(6));
               txtmail.setText(DBConnect.rs.getString(7));
                 txtPhone.setText(DBConnect.rs.getString(8));
                 lblImage.setIcon(ResizeImage(null, DBConnect.rs.getBytes(9)));
           joindate.setDate(DBConnect.rs.getDate(10));
           cboDep.setSelectedItem(11);
        cboDes.setSelectedItem(12);
 cboPay.setSelectedItem(13);
  txtInfo.setText(DBConnect.rs.getString(14));
            }
            con.close();
             btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
 btnSave.setEnabled(false);
        } catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null, ex);

        }
        employeenum = hid;
        ShowEmployees.dispose();
    }//GEN-LAST:event_selecttblActionPerformed

    private void cboDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepActionPerformed
        // TODO add your handling code here:
        fillDesignation();
    }//GEN-LAST:event_cboDepActionPerformed
       public void CenteredDialog(javax.swing.JDialog objFrame)
{
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
}  
        public final void FillTable(JTable table, String Query)
{
    try
    {
       Connection con = DBConnect.connect();
       DBConnect.ps = con.prepareStatement(Query);
      DBConnect.rs =  DBConnect.ps.executeQuery();
         
        //To remove previously added rows
        while(table.getRowCount() > 0) 
        {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns =  DBConnect.rs.getMetaData().getColumnCount();
        while( DBConnect.rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] =  DBConnect.rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow( DBConnect.rs.getRow()-1,row);
        }

        con.close();
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this,e);
    }
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JDialog ShowEmployees;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBrowse;
    private javax.swing.JButton btnCIr;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboDep;
    private javax.swing.JComboBox<String> cboDes;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboPay;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser joindate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel personalInfo;
    private javax.swing.JTextField searchemployee;
    private javax.swing.JButton selecttbl;
    private javax.swing.JTable tblshowemployees;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPanel workInfo;
    // End of variables declaration//GEN-END:variables
}
