/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ruth
 */
public class Holiday extends javax.swing.JFrame {
    Menu m = new Menu();
    Date date = new Date();
    TableFilter table = new TableFilter();
    DefaultTableModel model;
    
    String holiday = "SELECT * FROM `holiday` WHERE `Holiday` = ?";
    String hol_over = "SELECT holiday_overtime.*, employee.name FROM holiday_overtime, employee WHERE holiday_overtime.emp_id = employee.id AND holiday_overtime.emp_id = ?";

    /**
     * Creates new form Holiday
     */
    public Holiday() {
        initComponents();
        Jdate.setDate(date);
        bindCbo();
        table.Filter(tblHoliday, holiday, txtSearch1);
        table.Filter(tblHolOver, hol_over, txtSearch);
    }
    
    // Clear textfields and textareas
    public void clrFields (JPanel panel) {
for (Component C : panel.getComponents()) {    
    if (C instanceof JTextComponent){
        ((JTextComponent) C).setText(null);
    }
  }
}

    public void bindCbo (){
        Connection con = DBConnect.connect();
        try {
            DBConnect.st = con.createStatement();
            DBConnect.rs = DBConnect.st.executeQuery("SELECT * FROM holiday");
            while (DBConnect.rs.next()){
                cboHol.addItem(DBConnect.rs.getString(2));
            }
        } catch (SQLException e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holiday_overtime = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCIr = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        personalInfo2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cboHol = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHolOver = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        personalInfo3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        txtHoliday = new javax.swing.JTextField();
        btnCash = new javax.swing.JRadioButton();
        btnPer = new javax.swing.JRadioButton();
        btnNone = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoliday = new javax.swing.JTable();
        txtSearch1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCIrSDep = new javax.swing.JButton();
        btnSaveSDep = new javax.swing.JButton();
        btnUpdateSDep = new javax.swing.JButton();
        btnDelSDep = new javax.swing.JButton();
        btnBackSDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(18, 19, 34));
        Header.setMinimumSize(new java.awt.Dimension(776, 72));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payroll System");
        jLabel7.setIconTextGap(5);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HOLIDAY");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 10, 5));

        btnCIr.setBackground(new java.awt.Color(45, 43, 63));
        btnCIr.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnCIr.setForeground(new java.awt.Color(255, 255, 255));
        btnCIr.setText("Clear Fields");
        btnCIr.setBorderPainted(false);
        btnCIr.setContentAreaFilled(false);
        btnCIr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCIr.setOpaque(true);
        btnCIr.setPreferredSize(new java.awt.Dimension(74, 22));
        btnCIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCIrActionPerformed(evt);
            }
        });
        jPanel3.add(btnCIr);

        btnSave.setBackground(new java.awt.Color(45, 43, 63));
        btnSave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.setPreferredSize(new java.awt.Dimension(74, 22));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);

        btnUpdate.setBackground(new java.awt.Color(45, 43, 63));
        btnUpdate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setEnabled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.setPreferredSize(new java.awt.Dimension(74, 22));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate);

        btnDel.setBackground(new java.awt.Color(45, 43, 63));
        btnDel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setBorderPainted(false);
        btnDel.setContentAreaFilled(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setEnabled(false);
        btnDel.setOpaque(true);
        btnDel.setPreferredSize(new java.awt.Dimension(74, 22));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel3.add(btnDel);

        btnBack.setBackground(new java.awt.Color(18, 19, 34));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setOpaque(true);
        btnBack.setPreferredSize(new java.awt.Dimension(74, 22));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack);

        personalInfo2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Employee id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Date");

        Jdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Holiday");

        cboHol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_20px.png"))); // NOI18N

        javax.swing.GroupLayout personalInfo2Layout = new javax.swing.GroupLayout(personalInfo2);
        personalInfo2.setLayout(personalInfo2Layout);
        personalInfo2Layout.setHorizontalGroup(
            personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfo2Layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboHol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        personalInfo2Layout.setVerticalGroup(
            personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboHol)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tblHolOver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblHolOver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Holiday", "Emp_id", "Employee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHolOver.getTableHeader().setReorderingAllowed(false);
        tblHolOver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHolOverMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHolOver);
        if (tblHolOver.getColumnModel().getColumnCount() > 0) {
            tblHolOver.getColumnModel().getColumn(0).setResizable(false);
            tblHolOver.getColumnModel().getColumn(1).setResizable(false);
            tblHolOver.getColumnModel().getColumn(2).setResizable(false);
            tblHolOver.getColumnModel().getColumn(3).setResizable(false);
            tblHolOver.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_20px.png"))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setToolTipText("Search by department name");
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personalInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(personalInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("Holiday Overtime", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        personalInfo3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Overtime");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Holiday");

        txtRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRate.setText("0");
        txtRate.setToolTipText("Enter the overtime rate or amount number");
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });

        txtHoliday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCash.setBackground(new java.awt.Color(255, 255, 255));
        holiday_overtime.add(btnCash);
        btnCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        btnPer.setBackground(new java.awt.Color(255, 255, 255));
        btnPer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPer.setText("Percentage");
        btnPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerActionPerformed(evt);
            }
        });

        btnNone.setBackground(new java.awt.Color(255, 255, 255));
        btnNone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNone.setText("None");

        javax.swing.GroupLayout personalInfo3Layout = new javax.swing.GroupLayout(personalInfo3);
        personalInfo3.setLayout(personalInfo3Layout);
        personalInfo3Layout.setHorizontalGroup(
            personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfo3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(personalInfo3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(28, 28, 28)
                        .addComponent(txtHoliday)))
                .addGap(14, 14, 14))
            .addGroup(personalInfo3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personalInfo3Layout.setVerticalGroup(
            personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfo3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCash)
                        .addComponent(btnPer)
                        .addComponent(btnNone))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        tblHoliday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblHoliday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Holiday", "Overtime", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoliday.getTableHeader().setReorderingAllowed(false);
        tblHoliday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHolidayMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoliday);
        if (tblHoliday.getColumnModel().getColumnCount() > 0) {
            tblHoliday.getColumnModel().getColumn(0).setResizable(false);
            tblHoliday.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblHoliday.getColumnModel().getColumn(1).setResizable(false);
            tblHoliday.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblHoliday.getColumnModel().getColumn(2).setResizable(false);
            tblHoliday.getColumnModel().getColumn(3).setResizable(false);
        }

        txtSearch1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch1.setToolTipText("Search by name");
        txtSearch1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearch1CaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_20px.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 3, 10, 5));

        btnCIrSDep.setBackground(new java.awt.Color(45, 43, 63));
        btnCIrSDep.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnCIrSDep.setForeground(new java.awt.Color(255, 255, 255));
        btnCIrSDep.setText("Clear Fields");
        btnCIrSDep.setBorderPainted(false);
        btnCIrSDep.setContentAreaFilled(false);
        btnCIrSDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCIrSDep.setOpaque(true);
        btnCIrSDep.setPreferredSize(new java.awt.Dimension(74, 22));
        btnCIrSDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCIrSDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnCIrSDep);

        btnSaveSDep.setBackground(new java.awt.Color(45, 43, 63));
        btnSaveSDep.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnSaveSDep.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSDep.setText("Save");
        btnSaveSDep.setBorderPainted(false);
        btnSaveSDep.setContentAreaFilled(false);
        btnSaveSDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveSDep.setOpaque(true);
        btnSaveSDep.setPreferredSize(new java.awt.Dimension(74, 22));
        btnSaveSDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnSaveSDep);

        btnUpdateSDep.setBackground(new java.awt.Color(45, 43, 63));
        btnUpdateSDep.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnUpdateSDep.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateSDep.setText("Update");
        btnUpdateSDep.setBorderPainted(false);
        btnUpdateSDep.setContentAreaFilled(false);
        btnUpdateSDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateSDep.setEnabled(false);
        btnUpdateSDep.setOpaque(true);
        btnUpdateSDep.setPreferredSize(new java.awt.Dimension(74, 22));
        btnUpdateSDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdateSDep);

        btnDelSDep.setBackground(new java.awt.Color(45, 43, 63));
        btnDelSDep.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnDelSDep.setForeground(new java.awt.Color(255, 255, 255));
        btnDelSDep.setText("Delete");
        btnDelSDep.setBorderPainted(false);
        btnDelSDep.setContentAreaFilled(false);
        btnDelSDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelSDep.setEnabled(false);
        btnDelSDep.setOpaque(true);
        btnDelSDep.setPreferredSize(new java.awt.Dimension(74, 22));
        btnDelSDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelSDep);

        btnBackSDep.setBackground(new java.awt.Color(18, 19, 34));
        btnBackSDep.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btnBackSDep.setForeground(new java.awt.Color(255, 255, 255));
        btnBackSDep.setText("Back");
        btnBackSDep.setBorderPainted(false);
        btnBackSDep.setContentAreaFilled(false);
        btnBackSDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackSDep.setOpaque(true);
        btnBackSDep.setPreferredSize(new java.awt.Dimension(74, 22));
        btnBackSDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnBackSDep);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(personalInfo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearch1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(personalInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Holiday Management", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCIrActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_btnCIrActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        txtRate.setText("0.0");
        if(!txtName.getText().equals(""))
        {
                try {
                    Connection con = DBConnect.connect();

                    String sql = "INSERT INTO `holiday_overtime`(`date`, `holiday`, `emp_id`) VALUES (?, ?, ?)";
                    DBConnect.ps = con.prepareStatement(sql);
                    DBConnect.ps.setDate(1, (java.sql.Date) Jdate.getDate());
                    DBConnect.ps.setString(2, cboHol.getSelectedItem().toString());
                    DBConnect.ps.setInt(3, Integer.parseInt(txtName.getText()));
                    DBConnect.ps.execute();
                    JOptionPane.showMessageDialog(null, "Record Saved");
                    table.Filter(tblHolOver, hol_over, txtSearch);
                    clrFields(personalInfo2);
                    con.close();
                } catch (SQLException e ) {
                    JOptionPane.showMessageDialog(null, e);
                }
        }
        else
        JOptionPane.showMessageDialog(null, "Some fields are empty");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblHolOver.getModel();
            int selectedRow = tblHolOver.getSelectedRow();
            try {
                Connection con = DBConnect.connect();
                String query = "UPDATE `holiday_overtime` SET `date` = ?,`holiday` = ?,`emp_id` = ? WHERE `id` = ?";
                DBConnect.ps = con.prepareStatement(query);
                DBConnect.ps.setDate(1, (java.sql.Date) Jdate.getDate());
                DBConnect.ps.setString(2, cboHol.getSelectedItem().toString());
                DBConnect.ps.setInt(3, Integer.parseInt(txtName.getText()));
                DBConnect.ps.setInt(4, Integer.parseInt((String) model.getValueAt(selectedRow, 0)));

                DBConnect.ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record successfully updated");
                table.Filter(tblHoliday, holiday, txtSearch1);
                clrFields(personalInfo2);
                con.close();
            }
            catch (SQLException ex ) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblHolOver.getModel();
            int selectedRow = tblHolOver.getSelectedRow();
            try {
                Connection con = DBConnect.connect();
                String query = "DELETE FROM `holiday_overtime` WHERE `id` = ?";
                DBConnect.ps = con.prepareStatement(query);
                DBConnect.ps.setInt  (1, Integer.parseInt((String) model.getValueAt(selectedRow, 0)));
                DBConnect.ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "Record Deleted");
                table.Filter(tblHoliday, holiday, txtSearch1);
                clrFields(personalInfo2);
            } catch (SQLException e ) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblHolOverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHolOverMouseClicked
        try {
            // TODO add your handling code here:
            model = (DefaultTableModel) tblHolOver.getModel();
            int selectedRow = tblHolOver.getSelectedRow();
            
            Date dates = new SimpleDateFormat("dd-MM-yyyy").parse((String)model.getValueAt(selectedRow, 1));
            Jdate.setDate(dates);
            cboHol.setSelectedItem(model.getValueAt(selectedRow, 2));
            txtName.setText((String) model.getValueAt(selectedRow, 3));
        } catch (ParseException ex) {
            Logger.getLogger(Holiday.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHolOverMouseClicked

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        // TODO add your handling code here:
        table.Filter(tblHolOver, hol_over, txtSearch);
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void tblHolidayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHolidayMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) tblHoliday.getModel();
            int selectedRow = tblHoliday.getSelectedRow();
            
            txtHoliday.setText((String) model.getValueAt(selectedRow, 1));
            String overtime = ((String) model.getValueAt(selectedRow, 2));
            String rate = ((String) model.getValueAt(selectedRow, 3));
            txtRate.setText((String) model.getValueAt(selectedRow, 4));
            
            if (overtime == "Cash"){
                btnCash.setSelected(true);
            } else if (overtime == "Percentage"){
                btnPer.setSelected(true);
            } else if (overtime == "None"){
                btnNone.setSelected(true);
            }
            
    }//GEN-LAST:event_tblHolidayMouseClicked

    private void txtSearch1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearch1CaretUpdate
        // TODO add your handling code here:
        table.Filter(tblHoliday, holiday, txtSearch1);
    }//GEN-LAST:event_txtSearch1CaretUpdate

    private void btnCIrSDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCIrSDepActionPerformed
        // TODO add your handling code here:
        clrFields(personalInfo3);
    }//GEN-LAST:event_btnCIrSDepActionPerformed

    private void btnSaveSDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSDepActionPerformed
        // TODO add your handling code here:
        txtRate.setText("0.0");
        if(!txtHoliday.getText().equals(""))
        {
                try {
                    Connection con = DBConnect.connect();

                    String sql = "INSERT INTO `holiday`(`Holiday`, `overtime`, `rate`) VALUES (?, ?, ?)";
                    DBConnect.ps = con.prepareStatement(sql);
                    DBConnect.ps.setString(1, txtHoliday.getText());
                    if(btnCash.isSelected()){
                    DBConnect.ps.setString(2, "Cash");
                }
                else if(btnPer.isSelected())
                {
                    DBConnect.ps.setString(2, "Percent");
                }
                else if(btnNone.isSelected())
                {
                    DBConnect.ps.setString(2, "None");
                }
                    DBConnect.ps.setDouble(3, Double.parseDouble(txtRate.getText()));
                    DBConnect.ps.execute();
                    JOptionPane.showMessageDialog(null, "Record Saved");
                    table.Filter(tblHoliday, holiday, txtSearch1);
                    clrFields(personalInfo3);
                    bindCbo();
                    con.close();
                } catch (SQLException e ) {
                    JOptionPane.showMessageDialog(null, e);
                }
        }
        else
        JOptionPane.showMessageDialog(null, "Some fields are empty");
    }//GEN-LAST:event_btnSaveSDepActionPerformed

    private void btnUpdateSDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSDepActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblHoliday.getModel();
            int selectedRow = tblHoliday.getSelectedRow();
            try {
                Connection con = DBConnect.connect();
                String query = "UPDATE `holiday` SET `Holiday` = ?,`overtime` = ?,`rate` = ? WHERE `id` = ?";
                DBConnect.ps = con.prepareStatement(query);
                DBConnect.ps.setString(1, txtHoliday.getText());
                if(btnCash.isSelected()){
                    DBConnect.ps.setString(2, "Cash");
                }
                else if(btnPer.isSelected())
                {
                    DBConnect.ps.setString(2, "Percent");
                }
                else if(btnNone.isSelected())
                {
                    DBConnect.ps.setString(2, "None");
                }
                DBConnect.ps.setDouble(3, Double.parseDouble(txtRate.getText()));
                DBConnect.ps.setInt(4, Integer.parseInt((String) model.getValueAt(selectedRow, 0)));

                DBConnect.ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record successfully updated");
                table.Filter(tblHoliday, holiday, txtSearch1);
                clrFields(personalInfo3);
                bindCbo();
                con.close();
            }
            catch (SQLException ex ) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_btnUpdateSDepActionPerformed

    private void btnDelSDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSDepActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblHoliday.getModel();
            int selectedRow = tblHoliday.getSelectedRow();
            try {
                Connection con = DBConnect.connect();
                String query = "DELETE FROM `holiday` WHERE `id` = ?";
                DBConnect.ps = con.prepareStatement(query);
                DBConnect.ps.setInt  (1, Integer.parseInt((String) model.getValueAt(selectedRow, 0)));
                DBConnect.ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "Record Deleted");
                table.Filter(tblHoliday, holiday, txtSearch1);
                clrFields(personalInfo3);
                bindCbo();
            } catch (SQLException e ) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnDelSDepActionPerformed

    private void btnBackSDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSDepActionPerformed
        // TODO add your handling code here: m.setVisible(true);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackSDepActionPerformed

    private void btnPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCashActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holiday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holiday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holiday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holiday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Holiday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private com.toedter.calendar.JDateChooser Jdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackSDep;
    private javax.swing.JButton btnCIr;
    private javax.swing.JButton btnCIrSDep;
    private javax.swing.JRadioButton btnCash;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelSDep;
    private javax.swing.JRadioButton btnNone;
    private javax.swing.JRadioButton btnPer;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveSDep;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateSDep;
    private javax.swing.JComboBox<String> cboHol;
    private javax.swing.ButtonGroup holiday_overtime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel personalInfo2;
    private javax.swing.JPanel personalInfo3;
    private javax.swing.JTable tblHolOver;
    private javax.swing.JTable tblHoliday;
    private javax.swing.JTextField txtHoliday;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
